<a href="https://colab.research.google.com/github/kirankct22-sudo/chat-moderator/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([10,20,30,40])
print(a[0])
print (a[2])


10
30


In [ ]:
import numpy as np
a =  np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [ ]:
import numpy as np
a= np.array([
    [1,2,3],
    [4,5,6]
])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
a = np.array([

              [1,2,3],
              [4,5,6]
])
print(a.shape)

(2, 3)


In [ ]:
import numpy as np

a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [ ]:
import numpy as np
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(a+5)

[6 7 8 9]


In [ ]:
import numpy as np
a=np.array([10,20,30,40])
print(np.sum(a))

100


In [ ]:
import numpy as np
a=np.array([10,20,30,40])
print(np.min(a))
print (np.max(a))


10
40


In [ ]:
import numpy as np
a=np.array([10,20,30,40])
print(np.mean(a))

25.0


In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a[1:4])

[20 30 40]
